# Generated by Django 4.1.2 on 2022-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('seniority_level', models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Regular', 'Regular')], max_length=30)),
            ],
        ),
    ]
