# Generated by Django 4.1.2 on 2022-10-17 21:10

from django.db import migrations, models
import forms_demos_2.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, validators=[forms_demos_2.web.models.validate_text])),
                ('priority', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
