# Generated by Django 4.1.2 on 2022-10-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='age',
        ),
    ]
