# Generated by Django 4.1.2 on 2022-10-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_student_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
